baseURL = 'https://mariasolos.com/'
languageCode = 'en-us'
title = 'Maria Solano'
enableRobotsTXT = true

[caches]
    [caches.images]
        dir = ':cacheDir/images'

[markup]
    [markup.highlight]
        lineNos = true
        style = 'dracula'

[params]
    description = 'Personal website of Maria Solano'
